name: Pulumi
on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      stack-name:
        required: true
        type: string
jobs:
  pulumi:
    name: Pulumi
    runs-on: ubuntu-latest
    steps:
      # Check out repository
      - name: Check out repository
        uses: actions/checkout@v4
      # Prepare repo
      - name: Prepare repo
        uses: ./.github/actions/prepare-repo
      # Run pulumi
      - name: Pulumi
        uses: pulumi/actions@v5
        with:
          command: ${{ inputs.command }}
          stack-name: ${{ inputs.stack-name }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
